dictionaries:
  - en
excluded_files:
  - "poetry.lock"
  - "coverage.xml"
  - "test/data/malware_bulk_responses/"
  - "test/data/virustotal_bulk_responses/"

excluded_words:
  - ioc
  - iocs
  - shodan
  - Shodan
  - tablefmt
  - cprint
  - asctime
  - delim
  - emoijize
  - urlhaus
  - URLhaus
  - vxcube
  - vulns
  - tweepy
  - TweepError
  - noxfile
  - authentihash

spellcheck_filenames: true
