name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Run image"
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install dependencies
        run: poetry install
      - name: "Run linters"
        run: poetry run nox -e lint

